CREATE TABLE IF NOT EXISTS items (
  id UUID PRIMARY KEY NOT NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  price INTEGER NOT NULL,
  description TEXT NOT NULL
);
ALTER TABLE items ENABLE ELECTRIC;
